rg_name              = "SHIP-ROCK-DEV-RG"
rg_location          = "West Europe"
vnet_name            = "SHIP-ROCK-VNET"
vnet_address_space   = ["10.1.0.0/16"]
subnet_name          = "SHIPNET-01"
subnet_address_space = ["10.1.1.0/24"]
vm_name              = "SHIP-ROCK-DEV-VM-01"
vm_size              = "Standard_B1s"
vm_sku               = "2016-Datacenter"
vnet_DNS             = ["10.0.0.4"]
